<?php

namespace Tests;

use Zeroplex\Crawler\UrlSet\ArraySet;

class ArraySetTest extends \Codeception\Test\Unit
{
    protected ?ArraySet $set;
    protected function _before()
    {
        parent::_before();
        $this->set = new ArraySet();
    }

    protected function _after()
    {
        $this->set = null;
        parent::_after(); // TODO: Change the autogenerated stub
    }
}
