<?php

namespace Tests\Unit;

use Zeroplex\Crawler\UrlQueue\ArrayQueue;

class ArrayQueueTest extends \Codeception\Test\Unit
{
    protected ?ArrayQueue $queue;

    protected function _before()
    {
        parent::_before();
        $this->queue = new ArrayQueue();
    }

    protected function _after()
    {
        $this->queue = null;
        parent::_after(); // TODO: Change the autogenerated stub
    }
}
